<?php

/**
 * @file
 * Embedded Video Field provider file for france24 gallery rotator.
 */

function videocarousel_emfield_providers($module, $provider = NULL) {
  if ($module == 'emvideo') {
    return drupal_system_listing(".inc", drupal_get_path('module', 'videocarousel') ."/providers", 'name', 0);
  }
}

/**
 * Implementation of hook_views_api().
 */
function videocarousel_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'videocarousel'),
    //'path' => drupal_get_path('module', 'videocarousel') . '/includes',
  );
}


/**
 * Themes the Views Carousel View.
 */
function theme_videocarousel_view($view, $options = array(), $rows = array()) {
  // Remove the skin and skin path from the options.
  $skin = $options['skin'];
  $path = ($skin == 'custom') ? $options['skin_path'] : NULL;
  unset($options['skin'], $options['skin_path']);

  // Remove any empty options and convert any numbers to float values.
  foreach ($options as $key => $value) {
    if (is_numeric($value)) {
      $options[$key] = (float)$value;
    }
    if (empty($value)) {
      unset($options[$key]);
    }
  }

  // Use jCarousel to create the carousel.

  return theme('videocarousel', $rows, $options, $skin, $path, 'videocarousel-'. $view->name .'-'. $view->current_display, $view);
}


/**
 * Implementation of hook_theme().
 */
function videocarousel_theme($existing, $type, $theme, $path) {

    return array(
    'videocarousel' => array(
      'arguments' => array(
        'items' => array(),
        'options' => array(),
        'skin' => 'tango',
        'skin_path' => NULL,
        'id' => 'videocarousel',
        'view' => array(),
        
      ),
        'template' => 'videocarousel',
    ),
  );

}


/**
 * Process variables for videocarousel.tpl.php.
 *
 */
function template_preprocess_videocarousel(&$vars) {
  
  drupal_add_js(drupal_get_path('module', 'videocarousel') .'/videocarousel.js');
  drupal_add_css(drupal_get_path('module', 'videocarousel') .'/videocarousel.css');

  $options = $vars['options'];
  $skin = $vars['skin'];
  $skin_path = $vars['skin_path'];
  $id = $vars['id'];

  // add the caroussel
  $name = form_clean_id($id);
  jcarousel_add('#'. $name, $options, $skin, $skin_path);
  $vars['name'] = $name;

  // begin our loop
  $i = 0;
  $jq_container = null;
  $jq_listing = null;
  $jq_body = null;

  $i=0;
  $tab = array();
  $title = array();
  $body = array();
 
  $video_type = array();
  foreach ($vars['view']->style_plugin->rendered_fields as $view_item) {
    $i++;
 
    if ($view_item['field_emvideo_embed'] == "" && $view_item['field_local_video_fid'] != "" && $view_item['field_illustration_fid'] != "") {
      // here we have a local video file
      $video_type[$i] = "local";
      $filename = array();
      $filename = explode("/",$view_item['field_illustration_fid']);
      $filename = array_pop($filename);
      $video_type[$i] = $filename;
      $tab[$i] =  swf($view_item['field_local_video_fid'], array('flashvars' => array('image' => $filename)));
      $title[$i] = $view_item['title'];
      $body[$i] = $view_item['body'];
    }
    else {
      $video_type[$i] = "embed";
      $tab[$i] = $view_item['field_emvideo_embed'];
      $title[$i] = $view_item['title'];
      $body[$i] = $view_item['body'];
    }
  }

  $i=0;
  foreach ($vars['items'] as $item) {
    $i++;
    if ($i == 1) {
      $display = "display: block;";
    }
    else {
      $display = "display: none;";
    }
    if ($video_type[$i] != "embed") {
      $item = "<img src=".imagecache_create_url("videocarousel_item", $video_type[$i])." />";

    }

    $jq_container .= '<div style="'.$display.'" id="videocarousel-item-'.$i.'-main" class="videocarousel-video-container">'. $tab[$i] .'</div>';
    $jq_listing .= '<li id="videocarousel-item-'.$i.'" class="videocarousel-item">'. $item .'</li>';
    $jq_body .= '<h2 id="videocarousel-item-'.$i.'-title" style="'.$display.'" class="videocarousel-item-title">'. $title[$i] .'</h2><div id="videocarousel-item-'.$i.'-body" style="'.$display.'" class="videocarousel-item-body">'. $body[$i] .'</div>';
  }
  $vars['jq_container'] = $jq_container;
  $vars['jq_listing'] = $jq_listing;
  $vars['jq_body'] = $jq_body;
       
} 



/**
 * Implementation of hook_imagecache_default_presets().
 */

function videocarousel_imagecache_default_presets() {
  $presets = array();
  $presets['videocarousel_item'] = array (
    'presetname' => 'videocarousel_item',
    'actions' => array (
      0 => array (
        'weight' => '0',
        'module' => 'imagecache',
        'action' => 'imagecache_scale_and_crop',
        'data' => array (
          'width' => '120',
          'height' => '90',
        ),
      ),
    ),
  );
  return $presets;
}