<?php
/**
 * @file
 * Provides a Views style plugin for jQuery jcarousel.
 */


/**
 * Implementation of hook_views_api().
 */
function videocarousel_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'videocarousel'),
    //'path' => drupal_get_path('module', 'videocarousel') . '/includes',
  );
}


/**
 * Themes the Views Carousel View.
 */
function theme_videocarousel_view($view, $options = array(), $rows = array()) {
  // Remove the skin and skin path from the options.
  $skin = $options['skin'];
  $path = ($skin == 'custom') ? $options['skin_path'] : NULL;
  unset($options['skin'], $options['skin_path']);

  // Remove any empty options and convert any numbers to float values.
  foreach ($options as $key => $value) {
    if (is_numeric($value)) {
      $options[$key] = (float)$value;
    }
    if (empty($value)) {
      unset($options[$key]);
    }
  }

  // Use jCarousel to create the carousel.

  //dsm($view);
  return theme('videocarousel', $rows, $options, $skin, $path, 'videocarousel-'. $view->name .'-'. $view->current_display, $view);
}


/**
 * Implementation of hook_theme().
 */
function videocarousel_theme($existing, $type, $theme, $path) {

    return array(
    'videocarousel' => array(
      'arguments' => array(
        'items' => array(),
        'options' => array(),
        'skin' => 'tango',
        'skin_path' => NULL,
        'id' => 'videocarousel',
        'view' => array(),
        
      ),
        'template' => 'videocarousel',
    ),
  );

}


/**
 * Process variables for videocarousel.tpl.php.
 *
 *
 *
 */
function template_preprocess_videocarousel(&$vars) {
  //dsm($vars);
  drupal_add_js(drupal_get_path('module', 'videocarousel') .'/plop.js');
  drupal_add_css(drupal_get_path('module', 'videocarousel') .'/videocarousel.css');

  $options = $vars['options'];
  $skin = $vars['skin'];
  $skin_path = $vars['skin_path'];
  $id = $vars['id'];

  // add the caroussel
  $name = form_clean_id($id);
  jcarousel_add('#'. $name, $options, $skin, $skin_path);
  $vars['name'] = $name;

  // begin our loop
  $i = 0;
  $jq_container = null;
  $jq_listing = null;


  $i=0;
  $tab = array();
  foreach ($vars['view']->style_plugin->rendered_fields as $view_item) {
    $i++;
    $tab[$i] = $view_item['field_emvideo_embed'];
  }

  $i=0;
  //dsm($vars);
  foreach ($vars['items'] as $item) {
    $i++;
    $jq_container .= '<span style="display:none" id=carrou_'.$i.' class="all_carrou">'. $tab[$i] .'</span>';
    $jq_listing .= '<li onclick="javascript:show('.$i.')">'. $item .'</li>';
  }
  //$jq_container .= '</div>';
  //$jq_listing .= '</ul>';
  $vars['jq_container'] = $jq_container;
  $vars['jq_listing'] = $jq_listing;
       
}
